# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
