# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchro', '0003_auto_20170625_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('canjoinfreely', models.BooleanField()),
                ('couldjoin', models.BooleanField()),
                ('active', models.BooleanField()),
                ('show', models.BooleanField()),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(default='default', max_length=1024),
            preserve_default=False,
        ),
    ]
