# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchro', '0007_auto_20170705_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='slots',
            field=models.ManyToManyField(blank=True, to='synchro.Slot'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, to='synchro.Tag'),
        ),
    ]
