# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchro', '0008_auto_20170705_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='shortname',
            field=models.CharField(default='---', max_length=3),
            preserve_default=False,
        ),
    ]
