# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synchro', '0011_auto_20170707_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='keywords',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=8192),
        ),
    ]
